#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2014 uralbash <root@uralbash.ru>
#
# Distributed under terms of the MIT license.

sudo: false
language: python

notifications:
  email: "sacrud@uralbash.ru"
  email: "arkadiy@bk.ru"
  email: "ggift@mail.ru"
  irc:
    channels:
      - "chat.freenode.net#sacrud"
    on_success: change
    on_failure: always

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

matrix:
  include:
    - python: "pypy"
      env: NO_RSTLINT="enabled"

install:
  - pip install flake8 rstcheck
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install -r requirements-docs.txt
  - pip install .

script:
  # Pytest
  - py.test --cov=pyramid_sacrud --doctest-modules  tests/ pyramid_sacrud/

  # Styles check
  - if [ -z "$NO_RSTLINT" ]; then ./test.sh; fi

after_success:
  - pip install coveralls
  - coveralls
